//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sokoban.View.GameDocsComponents.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sokoban.View.GameDocsComponents.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xs:schema xmlns=&quot;http://www.martinvseticka.eu/SoTh&quot;
        ///           targetNamespace=&quot;http://www.martinvseticka.eu/SoTh&quot;
        ///           xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           elementFormDefault=&quot;qualified&quot;
        ///           attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///  &lt;!-- Game objects --&gt;
        ///  &lt;xs:element name=&quot;GameObject&quot; abstract=&quot;true&quot; type=&quot;GameObjectType&quot; /&gt;
        ///
        ///  &lt;xs:complexType name=&quot;GameObjectType&quot;&gt;
        ///    &lt;xs:sequence&gt;
        ///      &lt;xs:element name=&quot;Version&quot; type=&quot;xs: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuestSchema {
            get {
                return ResourceManager.GetString("QuestSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xs:schema id=&quot;XSDSchemaTest&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///&lt;!-- definition of simple elements --&gt;
        ///&lt;xs:element name=&quot;Name&quot; type=&quot;xs:string&quot;/&gt;
        ///&lt;xs:element name=&quot;File&quot; type=&quot;xs:string&quot;/&gt;
        ///
        ///&lt;xs:element name=&quot;League&quot;&gt;
        /// &lt;xs:complexType&gt;
        ///  &lt;xs:sequence&gt;
        ///   &lt;xs:element ref=&quot;Name&quot;/&gt;
        ///   &lt;xs:element ref=&quot;File&quot;/&gt;
        ///  &lt;/xs:sequence&gt;
        /// &lt;/xs:complexType&gt;
        ///&lt;/xs:element&gt;
        ///
        ///&lt;xs:element name=&quot;So [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuestsSchema {
            get {
                return ResourceManager.GetString("QuestsSchema", resourceCulture);
            }
        }
    }
}
